# Generated by Django 2.1.2 on 2018-12-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choiceid', models.IntegerField(primary_key=True, serialize=False)),
                ('flag', models.IntegerField()),
                ('pos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('filename', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Has_Embed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Embed')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('latexbody', models.TextField()),
                ('qdate', models.DateField(blank=True, null=True)),
                ('difficulty', models.IntegerField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicname', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='has_embed',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question'),
        ),
        migrations.AddField(
            model_name='choice_embed',
            name='filename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Embed'),
        ),
        migrations.AddField(
            model_name='choice_embed',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question'),
        ),
        migrations.AddField(
            model_name='belongsto',
            name='qid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Question'),
        ),
        migrations.AddField(
            model_name='belongsto',
            name='topicname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='has_embed',
            unique_together={('filename', 'qid')},
        ),
        migrations.AlterUniqueTogether(
            name='choice_embed',
            unique_together={('filename', 'qid', 'choiceid')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('choiceid', 'qid')},
        ),
        migrations.AlterUniqueTogether(
            name='belongsto',
            unique_together={('topicname', 'qid')},
        ),
    ]
