# Generated by Django 2.1.2 on 2018-12-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20181230_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choicetext',
            field=models.TextField(default='DefaultChoice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='pos',
            field=models.TextField(null=True),
        ),
    ]
