# Generated by Django 2.1.2 on 2019-01-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190101_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='q_topic',
        ),
        migrations.AddField(
            model_name='exam',
            name='q_topic',
            field=models.ManyToManyField(related_name='topic', to='application.Topic'),
        ),
    ]
