# Generated by Django 2.1.2 on 2018-12-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20181230_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
