# Generated by Django 2.1.2 on 2019-01-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AddField(
            model_name='exam',
            name='examid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
