# Generated by Django 2.1.2 on 2019-01-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190101_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choicetext',
            field=models.TextField(default=''),
        ),
    ]
